application:
  dev:
    debug_true: True
    log:
      disable_file_log_stream: False
      log_folder: "logs"
      disable_network_log_stream: False
      log_server_ip: "192.168.1.151"
    gym_server:
      server_ip: "192.168.1.151"
      secured_port: 8443
    user:
      username: "gymuser1"
      password: "yYs9kHDHE9wb3WUJXgKebKMDmCJyZFR3"
