application:
  dev:
    debug_true: True
    log:
      disable_file_log_stream: true
      log_folder: "logs"
      disable_network_log_stream: true
      log_server_ip: "192.168.1.151"
    gym_server:
      server_ip: "192.168.1.151"
      secured_port: 5000
